/*
 * Copyright (c) 2010, Leeds Metropolitan University
 *
 * This file is part of Bibliosight.
 *
 * Bibliosight is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Bibliosight is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Bibliosight. If not, see <http://www.gnu.org/licenses/>.
 *
 */

/*
 * ProxyOptionsDialog.java
 *
 * Created on 13-Nov-2009, 14:39:20
 */

package uk.ac.leedsmet.bibliosight.utilities;

import java.awt.Dialog;
import java.awt.Frame;
import javax.swing.JDialog;

/**
 * A dialog to set proxy options
 *
 * @author Mike Taylor
 */
public class ProxyOptionsDialog extends JDialog {

    protected String proxyHost_;
    protected Integer proxyPort_;

    /**
     * Creates new proxy options dialog with a frame parent
     * @param parent
     */
    public ProxyOptionsDialog(Frame parent) {
        super(parent);
        initDialog();
    }

    /**
     * Creates new proxy options dialog with a dialog parent
     * @param parent
     */
    public ProxyOptionsDialog(Dialog parent) {
        super(parent);
        initDialog();
    }

    /**
     * Initialise the dialog
     */
    private void initDialog()
    {
        setModal(true);
        initComponents();
    }

    /**
     * Returns the current value of the proxy host name property
     * @return
     */
    public String getProxyHost() {
        return proxyHost_;
    }

    /**
     * Sets the value of the proxy host name property
     * @param proxyHost
     */
    public void setProxyHost(String proxyHost) {
        proxyHost_ = proxyHost;

        // Need to update the display to reflect the value change
        updateDialogueDisplay();
    }

    /**
     * Returns the current value of the proxy host port property
     * @return
     */
    public Integer getProxyPort() {
        return proxyPort_;
    }

    /**
     * Sets the value of the proxy host port property
     * @param proxyHost
     */
    public void setProxyPort(Integer proxyPort) {
        proxyPort_ = proxyPort;

        // Need to update the display to reflect the value change
        updateDialogueDisplay();
    }

    /**
     * Sets the value of the proxy host port property
     * @param proxyHost
     */
    public void setProxyPort(String proxyPort) {
        try
        {
            proxyPort_ = Integer.parseInt(proxyPort);
        }
        catch (NumberFormatException ex)
        {
            proxyPort_ = null;
        }

        updateDialogueDisplay();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proxyHostLabel = new javax.swing.JLabel();
        proxyHostTextField = new javax.swing.JTextField();
        proxyPortLabel = new javax.swing.JLabel();
        proxyPortTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proxy settings");
        setModal(true);
        setResizable(false);

        proxyHostLabel.setText("Proxy host");

        proxyHostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxyHostTextFieldActionPerformed(evt);
            }
        });
        proxyHostTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                proxyHostTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                proxyHostTextFieldFocusLost(evt);
            }
        });

        proxyPortLabel.setText("Proxy port");

        proxyPortTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxyPortTextFieldActionPerformed(evt);
            }
        });
        proxyPortTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                proxyPortTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                proxyPortTextFieldFocusLost(evt);
            }
        });

        cancelButton.setMnemonic('c');
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setMnemonic('o');
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proxyHostLabel)
                            .addComponent(proxyPortLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(proxyPortTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(proxyHostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proxyHostLabel)
                    .addComponent(proxyHostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proxyPortLabel)
                    .addComponent(proxyPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proxyHostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyHostTextFieldActionPerformed
        setProxyHost(proxyHostTextField.getText());
    }//GEN-LAST:event_proxyHostTextFieldActionPerformed

    private void proxyPortTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyPortTextFieldActionPerformed
        setProxyPort(proxyPortTextField.getText());
    }//GEN-LAST:event_proxyPortTextFieldActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        proxyHost_ = null;
        proxyPort_ = null;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void proxyHostTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_proxyHostTextFieldFocusLost
    {//GEN-HEADEREND:event_proxyHostTextFieldFocusLost
        setProxyHost(proxyHostTextField.getText());
    }//GEN-LAST:event_proxyHostTextFieldFocusLost

    private void proxyPortTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_proxyPortTextFieldFocusLost
    {//GEN-HEADEREND:event_proxyPortTextFieldFocusLost
        setProxyPort(proxyPortTextField.getText());
    }//GEN-LAST:event_proxyPortTextFieldFocusLost

    private void proxyHostTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_proxyHostTextFieldFocusGained
    {//GEN-HEADEREND:event_proxyHostTextFieldFocusGained
        proxyHostTextField.selectAll();
    }//GEN-LAST:event_proxyHostTextFieldFocusGained

    private void proxyPortTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_proxyPortTextFieldFocusGained
    {//GEN-HEADEREND:event_proxyPortTextFieldFocusGained
        proxyPortTextField.selectAll();
    }//GEN-LAST:event_proxyPortTextFieldFocusGained

    /**
     * Updates the GUI elements with the current object data
     */
    private void updateDialogueDisplay()
    {
        proxyHostTextField.setText(proxyHost_);
        try
        {
            proxyPortTextField.setText(proxyPort_.toString());
        }
        catch (NullPointerException ex)
        {
            proxyPortTextField.setText(null);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel proxyHostLabel;
    private javax.swing.JTextField proxyHostTextField;
    private javax.swing.JLabel proxyPortLabel;
    private javax.swing.JTextField proxyPortTextField;
    // End of variables declaration//GEN-END:variables

}
